language: java
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
jdk:
  - oraclejdk8
env:
  - SCALA=2.11 JAVA_OPTS="-XX:MaxPermSize=512m -XX:ReservedCodeCacheSize=512m -Xmx512m -Xms256m" GRADLE_OPTS="-Xmx512m"
script: ./gradlew --stacktrace --no-daemon -i check_$SCALA -DscalaCompileOptions.useAnt=true
install: true
