language: java
sudo: false
jdk:
  - openjdk6
  - oraclejdk7
  - openjdk7
  - oraclejdk8
env:
  - SCALA=2.10 JAVA_OPTS="-XX:MaxPermSize=512m -XX:ReservedCodeCacheSize=512m" GRADLE_OPTS="-Dorg.gradle.daemon=false -Xmx512m"
  - SCALA=2.11 JAVA_OPTS="-XX:MaxPermSize=512m -XX:ReservedCodeCacheSize=512m" GRADLE_OPTS="-Dorg.gradle.daemon=false -Xmx512m"

script:
  - ./gradlew --stacktrace --no-daemon -i check_$SCALA install_$SCALA
  - if [[ "$SCALA" == "2.10" ]]; then sbt clean test; fi

install: ./gradlew -v
