language: java
sudo: false
jdk:
  - oraclejdk8
  - oraclejdk9
  - oraclejdk10
  - oraclejdk11
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
env:
  - JAVA_OPTS="-Xmx512m" GRADLE_OPTS="-Xms128m" PROJECT='-p core'
  - JAVA_OPTS="-Xmx512m" GRADLE_OPTS="-Xms128m" PROJECT=
script:
  - unset _JAVA_OPTIONS
  - env
  - ./gradlew --stacktrace --no-daemon -i $PROJECT build
install: true
