language: java
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
jdk:
  - oraclejdk8
  - oraclejdk9
  - oraclejdk10
  - openjdk8
env:
  - JAVA_OPTS="-Xmx512m" GRADLE_OPTS="-Xms128m"
script:
  - unset _JAVA_OPTIONS
  - env
  - ./gradlew --stacktrace --no-daemon -i build
install: true
