language: java
sudo: false
jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk8
env:
  - SCALA=2.12 JAVA_OPTS="-Xmx512m" GRADLE_OPTS="-Xms128m"
  - SCALA=nonscala JAVA_OPTS="-Xmx512m" GRADLE_OPTS="-Xms128m"
script:
  - unset _JAVA_OPTIONS
  - env
  - ./gradlew --stacktrace --no-daemon -i check_$SCALA
install: true
