language: java
sudo: false
jdk:
  - oraclejdk8
env:
  - SCALA=2.11 JAVA_OPTS="-XX:MaxPermSize=512m -XX:ReservedCodeCacheSize=512m"
script: ./gradlew --stacktrace --no-daemon -i check_$SCALA
install: true
