language: java
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
jdk:
  - oraclejdk7
  - openjdk7
  - oraclejdk8
env:
  - SCALA=2.11 JAVA_OPTS="-XX:MaxPermSize=512m -XX:ReservedCodeCacheSize=512m -Xmx512m" GRADLE_OPTS="-Xms128m"
script: ./gradlew --stacktrace --no-daemon -i check_$SCALA
install: true
