language: java
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
jdk:
  - oraclejdk7
  - openjdk7
env:
  - SCALA=2.11 JAVA_OPTS="-XX:MaxPermSize=512m -XX:ReservedCodeCacheSize=512m -Xmx512m" GRADLE_OPTS="-Xms128m"
  - SCALA=nonscala JAVA_OPTS="-XX:MaxPermSize=512m -XX:ReservedCodeCacheSize=512m -Xmx512m" GRADLE_OPTS="-Xms128m"
script:
  - unset _JAVA_OPTIONS
  - jdk_switcher use oraclejdk8
  - ./gradlew --stacktrace --no-daemon -i assemble_$SCALA
  - jdk_switcher use $TRAVIS_JDK_VERSION
  - cp build-jre7.gradle build.gradle
  - ./gradlew --stacktrace --no-daemon -i :pact-jvm-model:test :pact-jvm-pact-broker:test
  - ./gradlew --stacktrace --no-daemon -i test_$SCALA
install: true
